Infrastructure/api
dream-team-mb/xfive_reco pull request #1
Opened 2020-01-17 19:31 UTC by uSasha

Сделал API-шку и докерфайл.
Не уверен, что формат ответов совпадает с тем, что ожидает система, нужно будет проверят.

2020-01-17 23:11 UTC, confar commented on Dockerfile
> +FROM python:3.6.5-jessie
почему не 3.6.9?

2020-01-17 23:11 UTC, confar commented on src/api.py
> +    return 'OK', 200
мб тут запускать какую-то инициализацию?
чтобы эндпоинт не отдавал ок пока не готова модель?

2020-01-18 10:56 UTC, confar commented on src/api.py
> +    return {'item_ids': recommended}
jsonify({
        'recommended_products': [
            '4009f09b04', '15ccaa8685', 'bf07df54e1', '3e038662c0', '4dcf79043e',
            'f4599ca21a', '5cb93c9bc5', '4a29330c8d', '439498bce2', '343e841aaa',
            '0a46068efc', 'dc2001d036', '31dcf71bbd', '5645789fdf', '113e3ace79',
            'f098ee2a85', '53fc95e177', '080ace8748', '4c07cb5835', 'ea27d5dc75',
            'cbe1cd3bb3', '1c257c1a1b', 'f5e18af323', '5186e12ff4', '6d0f84a0ac',
            'f95785964a', 'ad865591c6', 'ac81544ebc', 'de25bccdaf', 'f43c12d228',
        ]
    })

указазано в solution при скачивании архива с материалами
https://retailhero.ai/c/recommender_system/overview

там есть пример сервера

2020-01-18 10:59 UTC, confar commented on src/config/__init__.py
> +    pass
в чем смысл этого код, у нас будут дев переменные? мне кажется этот модуль не нужен в целом

2020-01-18 13:57 UTC, confar requested changes
все хорошо, есть что поправить

2020-01-18 13:57 UTC, confar commented on Dockerfile
> +FROM python:3.6.5-jessie
мб даже 37?

2020-01-21 19:05 UTC, uSasha commented on src/api.py
> +    return 'OK', 200
Посмотрел еще раз, мы ведь инициализируем рекомендатор перед стартом сервера еще, т.е. на хелсчек не ответим, пока модель не готова.

2020-01-21 19:28 UTC, confar approved these changes

2020-01-21 19:35 UTC, merged